version: 2
updates:
- package-ecosystem: github-actions
  target-branch: bump-actions/setup-go
  directory: /
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
